// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZXSyuRo4xxbfdUdaLB5NDaVIY10wW4Dc',
    appId: '1:903084774731:android:f7fba2335d85fbbdc184ce',
    messagingSenderId: '903084774731',
    projectId: 'campusbuddy-sentinel',
    storageBucket: 'campusbuddy-sentinel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOM3exHI_Uu2kdKDnD8tYPvKMaUV5KsmM',
    appId: '1:903084774731:ios:f53a64f804b03c69c184ce',
    messagingSenderId: '903084774731',
    projectId: 'campusbuddy-sentinel',
    storageBucket: 'campusbuddy-sentinel.firebasestorage.app',
    iosBundleId: 'com.sentinel.campusBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOM3exHI_Uu2kdKDnD8tYPvKMaUV5KsmM',
    appId: '1:903084774731:ios:f53a64f804b03c69c184ce',
    messagingSenderId: '903084774731',
    projectId: 'campusbuddy-sentinel',
    storageBucket: 'campusbuddy-sentinel.firebasestorage.app',
    iosBundleId: 'com.sentinel.campusBuddy',
  );

}